### ISSUE TITLE
Unable to access container

### ISSUE THREAD

**Issue by jcouzy** [klutchell/unbound-docker#101] opened 2022-10-13 06:33 UTC
Hi, I am unable to access the unbound container to do analysis/troubleshooting.

docker exec -it unbound-test /bin/bash
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown

Why isn't there a shell installed in the container, doesn't work with other shells as well.

Thanks

**Comment by klutchell** [comment] 2022-10-13 12:22
Duplicate of https://github.com/klutchell/unbound-docker/issues/77

**Closed as not planned** 2022-10-13 12:22 UTC
